-- =====================================================================
-- Chá · Base de dados
-- Eu importo este ficheiro no phpMyAdmin (separador "Importar").
-- Ele cria a base "cha", as 8 tabelas e alguns dados de exemplo.
-- =====================================================================

-- Eu aviso o MySQL de que este ficheiro está em UTF-8.
-- Sem esta linha, os caracteres chineses podem ficar embaralhados (ex.: "è‘¡è„").
SET NAMES utf8mb4;

-- Eu apago a base antiga (se existir) para poder importar de novo sem erros.
DROP DATABASE IF EXISTS cha;

-- Eu uso utf8mb4 para os caracteres chineses (你好) e os acentos ficarem certos.
CREATE DATABASE cha
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE cha;


-- ---------------------------------------------------------------------
-- 1. UTILIZADORES
-- Aqui eu guardo quem tem conta no site.
-- A palavra-passe nunca fica em texto: eu guardo só o "hash" feito pelo PHP
-- com password_hash(). Por isso o campo tem 255 caracteres.
-- ---------------------------------------------------------------------
CREATE TABLE utilizadores (
  id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome            VARCHAR(80)  NOT NULL,
  email           VARCHAR(120) NOT NULL UNIQUE,
  palavra_passe   VARCHAR(255) NOT NULL,  -- só o hash
  nivel           ENUM('zero', 'basico', 'intermedio', 'avancado') NOT NULL DEFAULT 'zero',
  minutos_por_dia TINYINT UNSIGNED NOT NULL DEFAULT 60,
  sequencia_dias  SMALLINT UNSIGNED NOT NULL DEFAULT 0,  -- dias seguidos a estudar
  ultimo_estudo   DATE NULL,
  consentimento   DATETIME NOT NULL,  -- quando aceitou a política de privacidade (RGPD)
  criado_em       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 2. CIDADES
-- As 6 paradas da rota de 12 meses.
-- ---------------------------------------------------------------------
CREATE TABLE cidades (
  id       TINYINT UNSIGNED PRIMARY KEY,
  ordem    TINYINT UNSIGNED NOT NULL,
  nome     VARCHAR(40) NOT NULL,
  nome_zh  VARCHAR(10) NOT NULL,
  meses    VARCHAR(10) NOT NULL,
  tema     VARCHAR(60) NOT NULL,
  capa     VARCHAR(10) NULL     -- início do nome da foto de capa (ex.: "bj0"); NULL se ainda não houver
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 3. UNIDADES
-- Cada cidade tem 4 unidades. A chave estrangeira liga a unidade à cidade.
-- ---------------------------------------------------------------------
CREATE TABLE unidades (
  id         SMALLINT UNSIGNED PRIMARY KEY,
  cidade_id  TINYINT UNSIGNED NOT NULL,
  codigo     VARCHAR(5)  NOT NULL,   -- ex.: "1.2"
  titulo     VARCHAR(60) NOT NULL,
  foto       VARCHAR(30) NULL,   -- início do nome da foto (ex.: "bj2-cumprimentos"); NULL se ainda não houver
  FOREIGN KEY (cidade_id) REFERENCES cidades(id)
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 4. LIÇÕES
-- Cada unidade tem várias lições curtas.
-- ---------------------------------------------------------------------
CREATE TABLE licoes (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  unidade_id  SMALLINT UNSIGNED NOT NULL,
  ordem       TINYINT UNSIGNED NOT NULL,
  titulo      VARCHAR(80) NOT NULL,
  minutos     TINYINT UNSIGNED NOT NULL DEFAULT 15,
  explicacao  TEXT NULL,   -- texto curto que explica o tema da lição
  FOREIGN KEY (unidade_id) REFERENCES unidades(id)
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 5. PALAVRAS
-- O vocabulário. Cada palavra aparece pela primeira vez numa lição.
-- ---------------------------------------------------------------------
CREATE TABLE palavras (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  licao_id   INT UNSIGNED NOT NULL,
  hanzi      VARCHAR(20)  NOT NULL,
  pinyin     VARCHAR(40)  NOT NULL,
  traducao   VARCHAR(100) NOT NULL,
  FOREIGN KEY (licao_id) REFERENCES licoes(id)
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 5B. FRASES
-- Frases de exemplo de cada lição, para o aluno ouvir as palavras em contexto.
-- ---------------------------------------------------------------------
CREATE TABLE frases (
  id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  licao_id   INT UNSIGNED NOT NULL,
  hanzi      VARCHAR(60)  NOT NULL,
  pinyin     VARCHAR(120) NOT NULL,
  traducao   VARCHAR(160) NOT NULL,
  FOREIGN KEY (licao_id) REFERENCES licoes(id)
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 6. PROGRESSO
-- Que lições cada utilizador já terminou (relação N:N entre utilizadores e lições).
-- A chave primária tem duas colunas: o mesmo utilizador não termina a mesma lição duas vezes.
-- ON DELETE CASCADE: se eu eliminar o utilizador, o progresso dele também é eliminado (RGPD).
-- ---------------------------------------------------------------------
CREATE TABLE progresso (
  utilizador_id    INT UNSIGNED NOT NULL,
  licao_id      INT UNSIGNED NOT NULL,
  pontuacao     TINYINT UNSIGNED NOT NULL,   -- de 0 a 100
  concluida_em  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (utilizador_id, licao_id),
  FOREIGN KEY (utilizador_id) REFERENCES utilizadores(id) ON DELETE CASCADE,
  FOREIGN KEY (licao_id)   REFERENCES licoes(id)
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 7. REVISÕES (revisão espaçada / SRS)
-- Para cada palavra que o utilizador já estudou, eu guardo quando a deve rever.
-- Se ele acerta, o intervalo aumenta; se erra, volta a 1 dia.
-- ---------------------------------------------------------------------
CREATE TABLE revisoes (
  utilizador_id       INT UNSIGNED NOT NULL,
  palavra_id       INT UNSIGNED NOT NULL,
  intervalo_dias   SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  proxima_revisao  DATE NOT NULL,
  acertos          SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (utilizador_id, palavra_id),
  FOREIGN KEY (utilizador_id) REFERENCES utilizadores(id) ON DELETE CASCADE,
  FOREIGN KEY (palavra_id) REFERENCES palavras(id)
) ENGINE=InnoDB;


-- ---------------------------------------------------------------------
-- 8. CADERNO
-- As palavras que o utilizador guardou no caderno pessoal.
-- ---------------------------------------------------------------------
CREATE TABLE caderno (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  utilizador_id  INT UNSIGNED NOT NULL,
  hanzi       VARCHAR(20)  NOT NULL,
  pinyin      VARCHAR(40)  NOT NULL,
  traducao    VARCHAR(100) NOT NULL,
  criado_em   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (utilizador_id) REFERENCES utilizadores(id) ON DELETE CASCADE
) ENGINE=InnoDB;


-- =====================================================================
-- DADOS DE EXEMPLO
-- Eu não crio utilizadores aqui: eles são criados na página de registo,
-- porque é o PHP que faz o hash da palavra-passe.
-- =====================================================================

-- As 6 cidades da rota
INSERT INTO cidades (id, ordem, nome, nome_zh, meses, tema, capa) VALUES
  (1, 1, 'Pequim',   '北京', '1–2',   'Os sons do mandarim', 'bj0'),
  (2, 2, 'Xi''an',   '西安', '3–4',   'Comer e comprar',     'xa0'),
  (3, 3, 'Chengdu',  '成都', '5–6',   'O dia a dia',         'cd0'),
  (4, 4, 'Guilin',   '桂林', '7–8',   'Viajar',              'gl0'),
  (5, 5, 'Hangzhou', '杭州', '9–10',  'Contar e opinar',     NULL),
  (6, 6, 'Xangai',   '上海', '11–12', 'Trabalho e cidade',   NULL);

-- As 24 unidades (4 por cidade)
INSERT INTO unidades (id, cidade_id, codigo, titulo, foto) VALUES
  (1,  1, '1.1', 'Pinyin e tons', 'bj1-pinyin-tons'),
  (2,  1, '1.2', 'Olá, eu sou…', 'bj2-cumprimentos'),
  (3,  1, '1.3', 'Números e família', 'bj3-familia'),
  (4,  1, '1.4', 'Datas e horas', 'bj4-horas'),
  (5,  2, '2.1', 'Na banca de comida', 'xa1-banca'),
  (6,  2, '2.2', 'Quanto custa?', 'xa2-precos'),
  (7,  2, '2.3', 'Onde fica?', 'xa3-muralha'),
  (8,  2, '2.4', 'Pagar e planear', 'xa4-pagar'),
  (9,  3, '3.1', 'A minha rotina', 'cd1-rotina'),
  (10, 3, '3.2', 'Gostos e tempo livre', 'cd2-mahjong'),
  (11, 3, '3.3', 'Convites e planos', 'cd3-hotpot'),
  (12, 3, '3.4', 'Tempo e mensagens', 'cd4-chuva'),
  (13, 4, '4.1', 'Bilhetes e comboios', 'gl1-comboios'),
  (14, 4, '4.2', 'No hotel', NULL),
  (15, 4, '4.3', 'Descrever lugares', NULL),
  (16, 4, '4.4', 'Emergências', NULL),
  (17, 5, '5.1', 'Comparar', NULL),
  (18, 5, '5.2', 'Contar o passado', NULL),
  (19, 5, '5.3', 'Dar opinião', NULL),
  (20, 5, '5.4', 'Compras online e serviços', NULL),
  (21, 6, '6.1', 'Casa e serviços', NULL),
  (22, 6, '6.2', 'No trabalho', NULL),
  (23, 6, '6.3', 'Entrevista de emprego', NULL),
  (24, 6, '6.4', 'Ler a cidade', 'sh4-placas');

-- As 72 lições da rota (3 por unidade)
INSERT INTO licoes (id, unidade_id, ordem, titulo, minutos, explicacao) VALUES
  (1, 1, 1, 'Os 4 tons e o tom neutro', 15, 'Em mandarim, cada sílaba tem um tom. A mesma sílaba "ma" com tons diferentes dá palavras diferentes: mā (mãe), má (cânhamo), mǎ (cavalo) e mà (ralhar). O 1.º tom é alto e plano, o 2.º sobe, o 3.º desce e volta a subir e o 4.º cai de repente. O tom neutro é curto e leve, sem marca. Ouve cada palavra e repete em voz alta.'),
  (2, 1, 2, 'Iniciais do pinyin', 15, 'As iniciais são as consoantes do início da sílaba. Muitas parecem-se com as portuguesas, mas algumas são diferentes: o x soa como o "ch" de "chá", o q como o "tch" de "tchim-tchim", o h como o "r" de "rato", e zh, ch e sh dizem-se com a língua enrolada para trás.'),
  (3, 1, 3, 'Finais do pinyin', 15, 'As finais são a parte das vogais da sílaba. O ü diz-se com os lábios em bico, como o "u" francês. Nas finais com n, o "n" pronuncia-se no fim, sem som nasal. Nas finais com ng, o som fica no fundo da garganta, como no inglês "song".'),
  (4, 2, 1, 'Cumprimentos', 15, '你好 (nǐ hǎo) é o "olá" do dia a dia. Com pessoas mais velhas, professores ou clientes, usa 您好 (nín hǎo), que é mais educado. Repara que 你 e 好 são os dois do 3.º tom, por isso o 你 soa como 2.º tom: ní hǎo.'),
  (5, 2, 2, 'Qual é o teu nome?', 15, 'Para perguntar o nome usa 你叫什么名字？ (à letra, "tu chamas-te que nome?"). A resposta é 我叫 + o teu nome. Em mandarim, a palavra interrogativa fica no mesmo sítio onde fica a resposta.'),
  (6, 2, 3, 'De onde és?', 15, 'Para dizer a nacionalidade usa 是 (shì, "ser") + país + 人 (rén, pessoa). Para fazer uma pergunta de sim ou não, basta pôr 吗 no fim da frase. Para devolver a pergunta ("e tu?"), usa 呢.'),
  (7, 3, 1, 'Os números de 0 a 10', 15, 'Os números de 0 a 10 são a base de todos os outros. Aprende-os com o tom certo. O 一 (yī) muda de tom conforme a palavra seguinte, mas quando contas diz-se sempre yī.'),
  (8, 3, 2, 'Até 100 e a idade', 15, 'Os números até 100 formam-se como uma conta: 十一 = 10 + 1 = 11, 二十 = 2 × 10 = 20, 二十五 = 25. Para perguntar a idade a uma criança diz-se 你几岁？ A um adulto, é mais educado 你多大？ Na resposta, usa o número + 岁.'),
  (9, 3, 3, 'A minha família', 15, 'Para dizer quantas pessoas tens na família usa 有 (ter) com o classificador 个: 我有一个哥哥. Para negar, usa 没有, e nunca 不有. O 的 (de) indica posse: 我的妈妈 = a minha mãe.'),
  (10, 4, 1, 'Os dias da semana', 15, 'Os dias da semana são fáceis: 星期 (semana) + um número. Segunda-feira é 星期一, terça-feira é 星期二 e assim por diante até sábado, 星期六. O domingo é 星期天. Para perguntar o dia, troca o número por 几: 今天星期几？'),
  (11, 4, 2, 'As datas', 15, 'Em chinês a data vai do maior para o mais pequeno: ano, mês e dia. Os meses são número + 月: 九月 é setembro. O dia é número + 号. Para perguntar a data diz-se 今天几月几号？'),
  (12, 4, 3, 'As horas', 15, 'As horas dizem-se com 点 (diǎn), os minutos com 分 (fēn) e a meia hora com 半 (bàn). Para as duas horas usa-se 两点, e não 二点. A ordem da frase é: tempo, depois o que fazes. Diz-se "eu à tarde às duas horas tenho aula": 我下午两点上课.'),
  (13, 5, 1, 'Pedir comida', 15, 'Na banca, para pedir basta dizer 我要 (wǒ yào, "eu quero") + a quantidade + o que queres: 我要一个肉夹馍. Para seres mais educado, começa com 请给我 (qǐng gěi wǒ, "por favor, dá-me"). O 肉夹馍 é o petisco mais famoso de Xi''an: carne estufada dentro de um pão achatado.'),
  (14, 5, 2, 'Comer e beber', 15, 'Os verbos 吃 (chī, comer) e 喝 (hē, beber) vêm antes da comida ou da bebida, tal como em português. Para dizer o que te apetece usa 想 (xiǎng) + verbo: 我想喝茶 = apetece-me beber chá. Em Xi''an come-se muita massa, 面 (miàn), e muitos 饺子 (jiǎozi), uns pastéis cozidos recheados.'),
  (15, 5, 3, 'Os sabores', 15, 'Para descrever a comida usa 很 (hěn) + adjetivo: 很辣 = muito picante. Em mandarim não se põe 是 antes do adjetivo: diz-se 这个很好吃, e nunca 这个是好吃. Para dizer "demasiado" usa 太…了: 太辣了! Se não queres picante, diz 不要辣.'),
  (16, 6, 1, 'O dinheiro', 15, 'A moeda da China é o 人民币 (rénmínbì) e a unidade é o 元 (yuán). Na conversa, porém, diz-se 块 (kuài). A décima parte do yuan é o 毛 (máo). Para perguntar o preço diz-se 多少钱？ (à letra, "quanto dinheiro?"). A resposta é número + 块: 十五块.'),
  (17, 6, 2, 'Contar coisas', 15, 'Em mandarim, entre o número e a coisa aparece sempre um classificador. O mais comum é 个 (gè), mas muitas coisas têm o seu: 一杯茶 (um copo de chá), 一碗面 (uma tigela de massa), 一瓶水 (uma garrafa de água). Com classificadores, o 2 diz-se 两 e não 二: 两碗面.'),
  (18, 6, 3, 'Regatear', 15, 'Nos mercados de rua é normal negociar o preço, mas nas lojas com o preço marcado não. Diz 太贵了 (é demasiado caro) e propõe um valor com 可以吗？ ("pode ser?"). 便宜一点儿 quer dizer "um pouco mais barato". Se o preço não baixar, agradece com um sorriso e segue em frente.'),
  (19, 7, 1, 'Lugares da cidade', 15, 'Para perguntar onde fica um sítio usa 在哪儿？ (zài nǎr?): 厕所在哪儿？ = Onde fica a casa de banho? A resposta também usa 在: 在这儿 (aqui) ou 在那儿 (ali). Em Xi''an vais ouvir muitas vezes 城墙 (chéngqiáng), a muralha antiga que rodeia o centro da cidade.'),
  (20, 7, 2, 'Direções', 15, 'As palavras de posição vêm depois do sítio de referência: 银行旁边 = ao lado do banco (à letra, "banco lado"). Para indicar o caminho usa 往 (wǎng, "em direção a") + direção + verbo: 往左拐 = vira à esquerda, 往前走 = segue em frente.'),
  (21, 7, 3, 'Longe ou perto', 15, 'Para falar de distância usa 离 (lí): A 离 B 很近 = A fica perto de B. Para perguntar o caminho diz 去…怎么走？ ("para ir a… como se anda?"). O tempo que demora diz-se com 分钟 (minutos): 走路十分钟 = dez minutos a pé.'),
  (22, 8, 1, 'Pagar com o telemóvel', 15, 'Na China quase tudo se paga com o telemóvel, através do 微信 (Wēixìn, WeChat) ou do 支付宝 (Zhīfùbǎo, Alipay). O vendedor mostra um código QR e tu 扫码 (sǎo mǎ, lês o código). Mesmo assim, leva sempre algum 现金 (notas e moedas) para as bancas mais pequenas.'),
  (23, 8, 2, 'Planear o dia', 15, 'Para dizer o que queres fazer usa 想 + 去 + lugar. Para pôr as coisas por ordem usa 先…然后… (primeiro… depois…). Lembra-te de que o tempo vem antes do verbo: 明天上午我想去看兵马俑 = amanhã de manhã quero ir ver os Guerreiros de Terracota.'),
  (24, 8, 3, 'Pedir ajuda', 15, 'Quando não percebes, não faz mal: diz 我听不懂 (não percebo) e pede 请说慢一点儿 (fala mais devagar, por favor). Para fazer uma pergunta a um desconhecido começa com 请问 ("posso perguntar?"). E 可以帮我吗？ quer dizer "podes ajudar-me?".'),
  (25, 9, 1, 'Acordar e deitar', 15, 'Para contares a tua rotina, põe o tempo antes do verbo: 我每天早上七点起床 = todos os dias levanto-me às sete da manhã. Com 每天 (todos os dias) junta-se quase sempre 都 (dōu) antes do verbo: 我每天都吃早饭.'),
  (26, 9, 2, 'Trabalhar e estudar', 15, 'Muitas ações do dia a dia vêm aos pares com 上 e 下: 上班 (entrar no trabalho) e 下班 (sair do trabalho), 上课 e 下课 (entrar e sair da aula). O lugar onde fazes algo vem com 在, antes do verbo: 我在学校学习. Para dizer como vais usa 坐 + transporte + 去: 我坐地铁去公司.'),
  (27, 9, 3, 'O fim de semana', 15, 'Para dizer com que frequência fazes algo, a palavra fica antes do verbo: 常常 (muitas vezes) ou 有时候 (às vezes). 周末我常常在家休息 = ao fim de semana descanso muitas vezes em casa.'),
  (28, 10, 1, 'Do que gostas?', 15, 'Para falar de gostos usa 喜欢 (xǐhuan) + coisa, ou 喜欢 + verbo: 我喜欢音乐, 我喜欢看电影. Para perguntar podes juntar 吗, ou usar a forma "gostas não gostas": 你喜欢不喜欢？ Para dizer que gostas muito, usa 很喜欢.'),
  (29, 10, 2, 'Jogos e passatempos', 15, 'Em Chengdu a vida corre devagar: as pessoas passam horas no 茶馆 (casa de chá) e no parque a jogar 麻将 (mahjong). Para dizer que sabes fazer algo que aprendeste usa 会 (huì): 我会打麻将 = sei jogar mahjong. Para o mahjong e os desportos com bola usa-se o verbo 打: 打麻将, 打篮球.'),
  (30, 10, 3, 'O que achas?', 15, 'Para dares a tua opinião usa 觉得 (juéde, "achar"): 我觉得麻将很有意思. Para pedires a opinião de alguém põe 怎么样？ no fim da frase: 这个电影怎么样？ = que tal este filme? Para uma crítica suave usa 有点儿 antes do adjetivo: 有点儿辣 = é um bocado picante.'),
  (31, 11, 1, 'Convidar', 15, 'Para convidares alguém usa 我们一起…吧: 我们一起吃火锅吧！ = vamos comer hotpot juntos! Antes disso, podes perguntar se a pessoa está livre: 你今天晚上有空吗？ Quando alguém diz 我请客, quer dizer que vai pagar a conta.'),
  (32, 11, 2, 'Marcar hora e lugar', 15, 'Para marcar um encontro diz primeiro a hora e depois o lugar: 我们七点在门口见 = encontramo-nos às sete à porta. Para confirmar, os chineses dizem 不见不散 (à letra, "se não nos virmos, não saímos daqui"), que quer dizer que ninguém vai faltar.'),
  (33, 11, 3, 'No restaurante de hotpot', 15, 'Para chamares o empregado diz 服务员！ Para pedires a ementa, 请给我菜单. No hotpot de Chengdu podes escolher o 鸳鸯锅 (yuānyang guō), uma panela com duas metades: uma picante e outra não. No fim, para pedires a conta diz 买单！'),
  (34, 12, 1, 'O tempo que faz', 15, 'Para falar do tempo usa 天气 (tiānqì): 今天天气怎么样？ Em Chengdu o céu está muitas vezes nublado, 阴天. "Chover" diz-se 下雨 (à letra, "cair chuva"). Com 了 no fim mostras que algo mudou: 下雨了！ = começou a chover!'),
  (35, 12, 2, 'Mensagens no WeChat', 15, 'No dia a dia os chineses combinam quase tudo pelo 微信. Para pedir o contacto de alguém diz 我加你微信吧 ("vou adicionar-te no WeChat"). 发 (fā) é enviar: 发消息 (enviar uma mensagem). A pessoa que recebe vem com 给, antes do verbo: 给我发消息 = manda-me uma mensagem.'),
  (36, 12, 3, 'Mudar de planos', 15, 'Se tiveres de desmarcar, começa com 不好意思 (desculpa o incómodo), que é mais leve do que 对不起. Explica com 因为… 所以… (como… por isso…) e propõe outra data com 改天 (outro dia) ou 下次 (da próxima vez). A resposta simpática é 没关系 (não faz mal).'),
  (37, 13, 1, 'Comprar bilhetes', 15, 'Para comprar um bilhete diz 我要买一张去桂林的票. Repara: o destino (去桂林的) vem antes de 票, ligado por 的. Para bilhetes usa-se o classificador 张. Na China precisas do passaporte, 护照, para comprar bilhetes de comboio.'),
  (38, 13, 2, 'Horários', 15, 'Para perguntar a que horas parte o comboio diz 几点开？ e, para a chegada, 几点到？ A expressão 从…到… quer dizer "de… até…": 从成都到桂林 = de Chengdu a Guilin. Para dizer quanto tempo demora usa 要 + tempo: 要五个小时 = demora cinco horas.'),
  (39, 13, 3, 'Na estação', 15, 'Na estação procura as placas: 进站 (entrada), 出口 (saída) e 候车室 (sala de espera). Antes de entrar há controlo de segurança, 安检. Quando o teu comboio aparecer no painel, vai para o 检票口 indicado. Aqui 要 quer dizer "ter de": 行李要安检.'),
  (40, 14, 1, 'Fazer o check-in', 15, 'No hotel diz 我订了一个房间 (reservei um quarto). O 了 depois do verbo mostra que a ação já está feita. A receção vai pedir o 护照 e dar-te o 房卡, o cartão do quarto. Nos números de quartos e de telefone, o 1 diz-se muitas vezes yāo.'),
  (41, 14, 2, 'Pedir coisas', 15, 'Para pedires algo com educação usa 能不能…？ (pode ou não pode…?) ou 可以…吗？: 能不能给我一条毛巾？ Se alguma coisa não funciona, diz 坏了 (está avariado): 空调坏了.'),
  (42, 14, 3, 'Sair do hotel', 15, 'Para saíres do hotel diz 我要退房 (quero fazer o check-out). Se ainda vais passear, podes deixar a bagagem na receção: 可以寄存行李吗？ Se precisares de fatura, pede 发票. Para táxis usa-se o classificador 辆.'),
  (43, 15, 1, 'A paisagem', 15, 'Guilin é famosa pelas montanhas, 山, e pelo rio Li, 漓江. Para descrever usa 很 + adjetivo, ou 真 (zhēn, "mesmo") para mostrar emoção: 这儿真漂亮！ Para dizer que há algo num sítio usa 有: 桂林有很多山.'),
  (44, 15, 2, 'Antigo e moderno', 15, 'Quando o adjetivo vem antes do nome, junta-se 的: 很漂亮的城市 = uma cidade muito bonita. Com adjetivos de uma só sílaba, o 的 pode cair: 大城市, 老村子. Para juntar duas qualidades usa 也 (também): 很老，也很安静.'),
  (45, 15, 3, 'Tirar fotografias', 15, 'Para pedires a alguém que te tire uma fotografia diz 可以帮我拍一张照吗？ Antes de fotografares pessoas, pergunta sempre 可以拍照吗？ Em alguns templos e museus vais ver a placa 禁止拍照 (proibido fotografar).'),
  (46, 16, 1, 'Estou doente', 15, 'Para dizeres o que te dói usa a parte do corpo + 疼 (téng): 头疼 = dói-me a cabeça. 我不舒服 quer dizer "não me sinto bem". Na farmácia, 药店, podes pedir 药 (medicamento). Na China, o número da ambulância é o 120.'),
  (47, 16, 2, 'Pedir socorro', 15, '救命！ (jiùmìng) é "socorro!". Em caso de perigo, na China liga para a polícia, 110, ou para os bombeiros, 119. Para pedires ajuda urgente diz 快 (depressa) + o que precisas: 快叫救护车！'),
  (48, 16, 3, 'Perdi as minhas coisas', 15, 'Para dizeres que perdeste algo usa 丢了 (diū le): 我的钱包丢了. O 了 mostra que já aconteceu. Se estiveres perdido na cidade, diz 我迷路了. Se perderes o passaporte, fala com a polícia e com a Embaixada de Portugal, 葡萄牙大使馆.'),
  (49, 17, 1, 'Mais do que', 15, 'Para comparar usa A 比 B + adjetivo: 杭州比上海小 = Hangzhou é mais pequena do que Xangai. Com 比 não se usa 很. Para dizer "muito mais" põe 多了 no fim: 今天比昨天凉快多了. Para "ainda mais" usa 更.'),
  (50, 17, 2, 'Igual e diferente', 15, 'Para dizer que duas coisas são iguais usa A 跟 B 一样: 我跟你一样高 = sou tão alto como tu. Para negar a comparação usa 没有: 杭州没有上海大 = Hangzhou não é tão grande como Xangai. O superlativo faz-se com 最 (zuì): 最有名 = o mais famoso.'),
  (51, 17, 3, 'Escolher', 15, 'Para dar a escolher numa pergunta usa 还是 (ou): 你喝红茶还是绿茶？ Na resposta, repete só a opção que queres. Nas frases que não são perguntas, "ou" diz-se 或者. Para dizer que tanto faz, usa 都可以 ou 随便.'),
  (52, 18, 1, 'O que fizeste?', 15, 'Para contares algo que aconteceu, põe 了 depois do verbo: 我昨天去了西湖 = ontem fui ao Lago Oeste. Para negar o passado usa 没 e tira o 了: 我没去 = não fui. Para perguntar se já aconteceu, junta 没有 no fim: 你吃饭了没有？'),
  (53, 18, 2, 'Já alguma vez…?', 15, 'Para falares de experiências usa 过 (guo) depois do verbo: 我去过中国 = já estive na China. Para dizeres que nunca fizeste algo usa 从来没…过: 我从来没吃过臭豆腐 = nunca comi tofu fermentado. Para contar as vezes usa 次: 两次 = duas vezes.'),
  (54, 18, 3, 'Contar uma viagem', 15, 'Para contares uma história por ordem usa 先 (primeiro), 然后 (depois) e 最后 (por fim). 的时候 quer dizer "quando": 在杭州的时候 = quando estive em Hangzhou. Para dizer como correu usa 得: 玩得很开心 = diverti-me muito.'),
  (55, 19, 1, 'Concordar e discordar', 15, 'Para concordares diz 对 (certo) ou 我同意. Para discordares com educação usa 我不太同意 (não concordo muito). Os chineses costumam discordar de forma suave, sem um "não" direto. 你说得对 quer dizer "tens razão".'),
  (56, 19, 2, 'Porquê?', 15, 'Para perguntar a razão usa 为什么. Para acrescentar uma ideia usa 而且 (além disso). Para contrastar usa 但是 (mas). Em chinês, 虽然… 但是… (embora… mas…) usam-se juntos, ao contrário do português, onde basta "embora".'),
  (57, 19, 3, 'Dar conselhos', 15, 'Para dares um conselho usa 应该 (deves) ou 最好 (o melhor é): 你应该多休息. Para dizer que não é preciso usa 不用. 别 (bié) + verbo é uma ordem na negativa: 别担心！ = não te preocupes!'),
  (58, 20, 1, 'Comprar pela internet', 15, 'Hangzhou é a cidade do Alibaba, a empresa que criou o 淘宝 (Táobǎo), uma das maiores lojas online da China. Comprar pela internet diz-se 网购. A encomenda chega por 快递, e para perguntar quando chega diz 什么时候到？ Para roupa usa-se o classificador 件.'),
  (59, 20, 2, 'Trocas e devoluções', 15, 'Se o que compraste não serve, podes pedir 换 (trocar) ou 退货 (devolver). 太大了 e 太小了 explicam o problema. 合适 quer dizer que algo te fica bem. Para pedir outra cor, pergunta 有没有别的颜色？'),
  (60, 20, 3, 'Marcações e serviços', 15, 'Na China muitos serviços marcam-se pelo telemóvel: um corte de cabelo, uma mesa ou uma consulta. Para marcar diz 我想预约 + dia e hora. Para cancelar usa 取消. 外卖 é a comida que pedes para te entregarem em casa.'),
  (61, 21, 1, 'Procurar casa', 15, 'Para arrendar casa diz 租房子. O senhorio é o 房东 e a renda é o 房租: 房租一个月多少钱？ Em Xangai as casas são caras e muita gente partilha casa, 合租.'),
  (62, 21, 2, 'Arranjos em casa', 15, 'Quando alguma coisa avaria em casa, diz o objeto + 坏了: 洗衣机坏了. Para pedires que alguém venha arranjar usa 修 (xiū). O 一下 depois do verbo torna o pedido mais suave: 你能来修一下吗？ Aos técnicos chama-se 师傅.'),
  (63, 21, 3, 'O bairro', 15, 'Muitas pessoas vivem num 小区, um conjunto de prédios com portaria e seguranças. Os vizinhos são os 邻居. Atenção aos andares: na China o rés-do-chão é o 一楼, por isso o 十楼 é o nosso 9.º andar.'),
  (64, 22, 1, 'O escritório', 15, 'No escritório, 办公室, vais ouvir muitas vezes 开会 (ter uma reunião). O chefe é o 经理 e os colegas são os 同事. 在 antes do verbo mostra uma ação a decorrer: 经理在开会 = o diretor está em reunião.'),
  (65, 22, 2, 'E-mails e prazos', 15, 'Para falar de prazos usa 以前 (antes de) e 以后 (depois de), que vêm depois do tempo: 星期五以前 = antes de sexta-feira. 得 (děi) quer dizer "ter de": 我得加班 = tenho de fazer horas extra. Um e-mail é um 邮件.'),
  (66, 22, 3, 'Ao telefone', 15, 'Ao telefone, 喂 (wéi) é o nosso "está?". Para perguntares por alguém diz 请问，王经理在吗？ Se a pessoa não está, podem dizer-te 我让他给你回电话 (peço-lhe que te ligue de volta). 让 quer dizer "pedir a alguém que faça algo".'),
  (67, 23, 1, 'Apresentar-me', 15, 'Numa entrevista usa sempre 您 e apresenta-te com calma: nome, país e estudos. Para dizeres o que estudaste usa 我学的是…: 我学的是计算机 = estudei informática. 毕业 (bìyè) é acabar o curso.'),
  (68, 23, 2, 'Experiência e competências', 15, 'Para falares da experiência usa 在…工作过: 我在一家公司工作过两年. 家 é o classificador de empresas e lojas. Para dizeres o que sabes fazer usa 会: 我会说葡萄牙语和英语.'),
  (69, 23, 3, 'Perguntas e salário', 15, 'No fim da entrevista é normal fazeres perguntas. O salário é o 工资 e o contrato é o 合同. Para perguntar o horário diz 每天工作几个小时？ Termina sempre com um agradecimento: 谢谢您给我这个机会.'),
  (70, 24, 1, 'Placas de rua', 15, 'As placas de rua mostram os pontos cardeais: 东 (este), 南 (sul), 西 (oeste) e 北 (norte). 路 e 街 querem dizer "rua". Muitas ruas de Xangai têm o nome de outras cidades chinesas, como a 南京路 (Rua de Nanquim). 路口 é o cruzamento.'),
  (71, 24, 2, 'Avisos e proibições', 15, 'Os avisos usam palavras curtas e formais. 禁止 (proibido) e 请勿 (por favor, não) aparecem em muitos sítios: 禁止吸烟 (proibido fumar), 请勿触摸 (não tocar). 注意 é "atenção", e 小心地滑 quer dizer "cuidado, piso escorregadio".'),
  (72, 24, 3, 'Metro e lojas', 15, 'No metro de Xangai, as linhas são 号线: 二号线 = linha 2. Mudar de linha diz-se 换乘. Nas lojas, 营业时间 é o horário de funcionamento. Atenção a 打折: 打八折 quer dizer que pagas 80% do preço, ou seja, tens 20% de desconto.');

-- Palavras novas de cada lição
INSERT INTO palavras (licao_id, hanzi, pinyin, traducao) VALUES
  (1, '妈', 'mā', 'mãe'),
  (1, '麻', 'má', 'cânhamo / dormente'),
  (1, '马', 'mǎ', 'cavalo'),
  (1, '骂', 'mà', 'ralhar'),
  (1, '吗', 'ma', 'partícula de pergunta'),
  (2, '八', 'bā', 'oito'),
  (2, '大', 'dà', 'grande'),
  (2, '高', 'gāo', 'alto'),
  (2, '鸡', 'jī', 'galinha'),
  (2, '七', 'qī', 'sete'),
  (2, '心', 'xīn', 'coração'),
  (2, '中', 'zhōng', 'meio'),
  (2, '吃', 'chī', 'comer'),
  (2, '书', 'shū', 'livro'),
  (2, '人', 'rén', 'pessoa'),
  (3, '爱', 'ài', 'amar / amor'),
  (3, '杯', 'bēi', 'copo'),
  (3, '好', 'hǎo', 'bom / bem'),
  (3, '狗', 'gǒu', 'cão'),
  (3, '饭', 'fàn', 'arroz / refeição'),
  (3, '名', 'míng', 'nome'),
  (3, '绿', 'lǜ', 'verde'),
  (3, '鱼', 'yú', 'peixe'),
  (4, '你好', 'nǐ hǎo', 'olá'),
  (4, '您好', 'nín hǎo', 'olá (formal)'),
  (4, '谢谢', 'xièxie', 'obrigado'),
  (4, '不客气', 'bú kèqi', 'de nada'),
  (4, '对不起', 'duìbuqǐ', 'desculpa'),
  (4, '再见', 'zàijiàn', 'adeus'),
  (5, '我', 'wǒ', 'eu'),
  (5, '你', 'nǐ', 'tu'),
  (5, '您', 'nín', 'o senhor / a senhora'),
  (5, '叫', 'jiào', 'chamar-se'),
  (5, '什么', 'shénme', 'o quê / que'),
  (5, '名字', 'míngzi', 'nome'),
  (6, '是', 'shì', 'ser'),
  (6, '吗', 'ma', 'partícula de pergunta (sim ou não)'),
  (6, '呢', 'ne', 'e tu? (partícula)'),
  (6, '哪', 'nǎ', 'qual'),
  (6, '国', 'guó', 'país'),
  (6, '中国人', 'Zhōngguó rén', 'chinês / chinesa'),
  (6, '巴西人', 'Bāxī rén', 'brasileiro / brasileira'),
  (6, '葡萄牙人', 'Pútáoyá rén', 'português / portuguesa'),
  (7, '零', 'líng', 'zero'),
  (7, '一', 'yī', 'um'),
  (7, '二', 'èr', 'dois'),
  (7, '三', 'sān', 'três'),
  (7, '四', 'sì', 'quatro'),
  (7, '五', 'wǔ', 'cinco'),
  (7, '六', 'liù', 'seis'),
  (7, '七', 'qī', 'sete'),
  (7, '八', 'bā', 'oito'),
  (7, '九', 'jiǔ', 'nove'),
  (7, '十', 'shí', 'dez'),
  (8, '十一', 'shíyī', 'onze'),
  (8, '二十', 'èrshí', 'vinte'),
  (8, '一百', 'yìbǎi', 'cem'),
  (8, '岁', 'suì', 'anos (de idade)'),
  (8, '几', 'jǐ', 'quantos (números pequenos)'),
  (8, '多大', 'duō dà', 'que idade'),
  (9, '爸爸', 'bàba', 'pai'),
  (9, '妈妈', 'māma', 'mãe'),
  (9, '哥哥', 'gēge', 'irmão mais velho'),
  (9, '姐姐', 'jiějie', 'irmã mais velha'),
  (9, '弟弟', 'dìdi', 'irmão mais novo'),
  (9, '妹妹', 'mèimei', 'irmã mais nova'),
  (9, '家', 'jiā', 'casa / família'),
  (9, '有', 'yǒu', 'ter'),
  (9, '没有', 'méiyǒu', 'não ter'),
  (9, '个', 'gè', 'classificador geral'),
  (9, '的', 'de', 'partícula de posse'),
  (10, '星期', 'xīngqī', 'semana'),
  (10, '星期一', 'xīngqīyī', 'segunda-feira'),
  (10, '星期三', 'xīngqīsān', 'quarta-feira'),
  (10, '星期六', 'xīngqīliù', 'sábado'),
  (10, '星期天', 'xīngqītiān', 'domingo'),
  (10, '今天', 'jīntiān', 'hoje'),
  (10, '明天', 'míngtiān', 'amanhã'),
  (10, '昨天', 'zuótiān', 'ontem'),
  (11, '年', 'nián', 'ano'),
  (11, '月', 'yuè', 'mês'),
  (11, '号', 'hào', 'dia (do mês)'),
  (11, '生日', 'shēngrì', 'aniversário'),
  (12, '点', 'diǎn', 'hora (no relógio)'),
  (12, '半', 'bàn', 'meia'),
  (12, '分', 'fēn', 'minuto'),
  (12, '现在', 'xiànzài', 'agora'),
  (12, '上午', 'shàngwǔ', 'manhã'),
  (12, '下午', 'xiàwǔ', 'tarde'),
  (12, '两', 'liǎng', 'dois (a contar coisas)'),
  (13, '要', 'yào', 'querer'),
  (13, '请', 'qǐng', 'por favor'),
  (13, '给', 'gěi', 'dar'),
  (13, '肉夹馍', 'ròujiāmó', 'pão recheado com carne'),
  (13, '这个', 'zhège', 'este / isto'),
  (13, '那个', 'nàge', 'aquele / aquilo'),
  (13, '老板', 'lǎobǎn', 'dono (da banca ou loja)'),
  (14, '吃', 'chī', 'comer'),
  (14, '喝', 'hē', 'beber'),
  (14, '想', 'xiǎng', 'apetecer / querer'),
  (14, '水', 'shuǐ', 'água'),
  (14, '茶', 'chá', 'chá'),
  (14, '面', 'miàn', 'massa'),
  (14, '饺子', 'jiǎozi', 'pastéis cozidos (jiaozi)'),
  (14, '米饭', 'mǐfàn', 'arroz cozido'),
  (15, '很', 'hěn', 'muito'),
  (15, '太', 'tài', 'demasiado'),
  (15, '辣', 'là', 'picante'),
  (15, '甜', 'tián', 'doce'),
  (15, '咸', 'xián', 'salgado'),
  (15, '好吃', 'hǎochī', 'saboroso (comida)'),
  (15, '好喝', 'hǎohē', 'saboroso (bebida)'),
  (15, '不要', 'bú yào', 'não querer'),
  (16, '钱', 'qián', 'dinheiro'),
  (16, '多少', 'duōshao', 'quanto'),
  (16, '块', 'kuài', 'yuan (na conversa)'),
  (16, '元', 'yuán', 'yuan (por escrito)'),
  (16, '毛', 'máo', 'dez cêntimos de yuan'),
  (16, '人民币', 'rénmínbì', 'renminbi (moeda chinesa)'),
  (16, '一共', 'yígòng', 'no total'),
  (17, '杯', 'bēi', 'copo (classificador)'),
  (17, '碗', 'wǎn', 'tigela (classificador)'),
  (17, '瓶', 'píng', 'garrafa (classificador)'),
  (17, '斤', 'jīn', 'meio quilo'),
  (17, '张', 'zhāng', 'classificador de coisas planas'),
  (17, '苹果', 'píngguǒ', 'maçã'),
  (18, '贵', 'guì', 'caro'),
  (18, '便宜', 'piányi', 'barato'),
  (18, '一点儿', 'yìdiǎnr', 'um pouco'),
  (18, '可以', 'kěyǐ', 'poder / pode ser'),
  (18, '买', 'mǎi', 'comprar'),
  (18, '卖', 'mài', 'vender'),
  (18, '吧', 'ba', 'partícula de sugestão'),
  (19, '在', 'zài', 'estar em / ficar'),
  (19, '哪儿', 'nǎr', 'onde'),
  (19, '这儿', 'zhèr', 'aqui'),
  (19, '那儿', 'nàr', 'ali'),
  (19, '厕所', 'cèsuǒ', 'casa de banho'),
  (19, '地铁站', 'dìtiězhàn', 'estação de metro'),
  (19, '银行', 'yínháng', 'banco'),
  (19, '城墙', 'chéngqiáng', 'muralha da cidade'),
  (20, '左', 'zuǒ', 'esquerda'),
  (20, '右', 'yòu', 'direita'),
  (20, '前', 'qián', 'frente'),
  (20, '后面', 'hòumiàn', 'atrás'),
  (20, '旁边', 'pángbiān', 'ao lado'),
  (20, '往', 'wǎng', 'em direção a'),
  (20, '拐', 'guǎi', 'virar'),
  (20, '一直', 'yìzhí', 'sempre a direito'),
  (21, '远', 'yuǎn', 'longe'),
  (21, '近', 'jìn', 'perto'),
  (21, '离', 'lí', 'a (distância de)'),
  (21, '去', 'qù', 'ir'),
  (21, '走', 'zǒu', 'andar / ir'),
  (21, '怎么', 'zěnme', 'como'),
  (21, '分钟', 'fēnzhōng', 'minutos (de duração)'),
  (21, '走路', 'zǒulù', 'ir a pé'),
  (21, '打车', 'dǎchē', 'apanhar um táxi'),
  (22, '手机', 'shǒujī', 'telemóvel'),
  (22, '微信', 'Wēixìn', 'WeChat'),
  (22, '支付宝', 'Zhīfùbǎo', 'Alipay'),
  (22, '扫码', 'sǎo mǎ', 'ler o código QR'),
  (22, '付钱', 'fù qián', 'pagar'),
  (22, '现金', 'xiànjīn', 'notas e moedas'),
  (22, '用', 'yòng', 'usar'),
  (23, '先', 'xiān', 'primeiro'),
  (23, '然后', 'ránhòu', 'depois'),
  (23, '看', 'kàn', 'ver'),
  (23, '兵马俑', 'Bīngmǎyǒng', 'Guerreiros de Terracota'),
  (23, '晚上', 'wǎnshang', 'à noite'),
  (23, '我们', 'wǒmen', 'nós'),
  (23, '一起', 'yìqǐ', 'juntos'),
  (24, '请问', 'qǐngwèn', 'posso perguntar?'),
  (24, '帮', 'bāng', 'ajudar'),
  (24, '听', 'tīng', 'ouvir'),
  (24, '懂', 'dǒng', 'perceber'),
  (24, '说', 'shuō', 'falar / dizer'),
  (24, '慢', 'màn', 'devagar'),
  (24, '再', 'zài', 'outra vez'),
  (24, '中文', 'Zhōngwén', 'chinês (língua)'),
  (25, '起床', 'qǐchuáng', 'levantar-se'),
  (25, '睡觉', 'shuìjiào', 'dormir / deitar-se'),
  (25, '洗澡', 'xǐzǎo', 'tomar banho'),
  (25, '早上', 'zǎoshang', 'de manhã (cedo)'),
  (25, '早饭', 'zǎofàn', 'pequeno-almoço'),
  (25, '每天', 'měitiān', 'todos os dias'),
  (25, '都', 'dōu', 'sempre / todos'),
  (26, '工作', 'gōngzuò', 'trabalhar / trabalho'),
  (26, '学习', 'xuéxí', 'estudar'),
  (26, '上班', 'shàngbān', 'entrar no trabalho'),
  (26, '下班', 'xiàbān', 'sair do trabalho'),
  (26, '上课', 'shàngkè', 'ter aula'),
  (26, '学校', 'xuéxiào', 'escola'),
  (26, '公司', 'gōngsī', 'empresa'),
  (26, '坐', 'zuò', 'ir de (transporte) / sentar-se'),
  (27, '周末', 'zhōumò', 'fim de semana'),
  (27, '休息', 'xiūxi', 'descansar'),
  (27, '常常', 'chángcháng', 'muitas vezes'),
  (27, '有时候', 'yǒu shíhou', 'às vezes'),
  (27, '做饭', 'zuòfàn', 'cozinhar'),
  (27, '朋友', 'péngyou', 'amigo'),
  (27, '见', 'jiàn', 'ver / encontrar'),
  (28, '喜欢', 'xǐhuan', 'gostar'),
  (28, '音乐', 'yīnyuè', 'música'),
  (28, '电影', 'diànyǐng', 'filme'),
  (28, '运动', 'yùndòng', 'desporto'),
  (28, '看书', 'kàn shū', 'ler'),
  (28, '唱歌', 'chànggē', 'cantar'),
  (28, '跳舞', 'tiàowǔ', 'dançar'),
  (29, '会', 'huì', 'saber (fazer algo aprendido)'),
  (29, '打', 'dǎ', 'jogar (mahjong, bola)'),
  (29, '麻将', 'májiàng', 'mahjong'),
  (29, '教', 'jiāo', 'ensinar'),
  (29, '茶馆', 'cháguǎn', 'casa de chá'),
  (29, '公园', 'gōngyuán', 'parque'),
  (29, '篮球', 'lánqiú', 'basquetebol'),
  (30, '觉得', 'juéde', 'achar'),
  (30, '怎么样', 'zěnmeyàng', 'que tal'),
  (30, '有意思', 'yǒu yìsi', 'interessante'),
  (30, '没意思', 'méi yìsi', 'aborrecido'),
  (30, '好玩', 'hǎowán', 'divertido'),
  (30, '非常', 'fēicháng', 'muitíssimo'),
  (30, '有点儿', 'yǒudiǎnr', 'um bocado (crítica)'),
  (31, '有空', 'yǒu kòng', 'estar livre'),
  (31, '火锅', 'huǒguō', 'hotpot (panela ao centro da mesa)'),
  (31, '请客', 'qǐngkè', 'pagar a conta (a convidar)'),
  (31, '忙', 'máng', 'ocupado'),
  (31, '行', 'xíng', 'está bem / pode ser'),
  (31, '当然', 'dāngrán', 'claro'),
  (32, '见面', 'jiànmiàn', 'encontrar-se'),
  (32, '等', 'děng', 'esperar'),
  (32, '门口', 'ménkǒu', 'à porta / entrada'),
  (32, '饭馆', 'fànguǎn', 'restaurante'),
  (32, '到', 'dào', 'chegar'),
  (32, '晚', 'wǎn', 'tarde (atrasado)'),
  (32, '不见不散', 'bú jiàn bú sàn', 'lá estaremos sem falta'),
  (33, '服务员', 'fúwùyuán', 'empregado de mesa'),
  (33, '菜单', 'càidān', 'ementa'),
  (33, '点菜', 'diǎncài', 'pedir os pratos'),
  (33, '买单', 'mǎidān', 'pedir a conta'),
  (33, '微辣', 'wēilà', 'pouco picante'),
  (33, '鸳鸯锅', 'yuānyang guō', 'panela com duas metades'),
  (33, '筷子', 'kuàizi', 'pauzinhos'),
  (34, '天气', 'tiānqì', 'tempo (meteorológico)'),
  (34, '下雨', 'xià yǔ', 'chover'),
  (34, '热', 'rè', 'quente'),
  (34, '冷', 'lěng', 'frio'),
  (34, '阴天', 'yīntiān', 'céu nublado'),
  (34, '晴天', 'qíngtiān', 'céu limpo'),
  (34, '伞', 'sǎn', 'guarda-chuva'),
  (34, '带', 'dài', 'levar (consigo)'),
  (34, '夏天', 'xiàtiān', 'verão'),
  (35, '发', 'fā', 'enviar'),
  (35, '消息', 'xiāoxi', 'mensagem'),
  (35, '语音', 'yǔyīn', 'mensagem de voz'),
  (35, '加', 'jiā', 'adicionar'),
  (35, '回', 'huí', 'responder / voltar'),
  (35, '电话', 'diànhuà', 'telefone'),
  (35, '打电话', 'dǎ diànhuà', 'telefonar'),
  (36, '不好意思', 'bù hǎoyìsi', 'desculpa (o incómodo)'),
  (36, '能', 'néng', 'poder'),
  (36, '因为', 'yīnwèi', 'porque / como'),
  (36, '所以', 'suǒyǐ', 'por isso'),
  (36, '改天', 'gǎitiān', 'outro dia'),
  (36, '下次', 'xià cì', 'da próxima vez'),
  (36, '迟到', 'chídào', 'chegar atrasado'),
  (36, '没关系', 'méi guānxi', 'não faz mal'),
  (37, '票', 'piào', 'bilhete'),
  (37, '火车', 'huǒchē', 'comboio'),
  (37, '高铁', 'gāotiě', 'comboio de alta velocidade'),
  (37, '车站', 'chēzhàn', 'estação'),
  (37, '护照', 'hùzhào', 'passaporte'),
  (37, '单程', 'dānchéng', 'só ida'),
  (37, '往返', 'wǎngfǎn', 'ida e volta'),
  (38, '出发', 'chūfā', 'partir'),
  (38, '开', 'kāi', 'partir (veículo) / abrir'),
  (38, '从', 'cóng', 'de (origem)'),
  (38, '小时', 'xiǎoshí', 'hora (de duração)'),
  (38, '大概', 'dàgài', 'mais ou menos'),
  (38, '车次', 'chēcì', 'número do comboio'),
  (38, '站台', 'zhàntái', 'plataforma'),
  (39, '进站', 'jìnzhàn', 'entrada (na estação)'),
  (39, '出口', 'chūkǒu', 'saída'),
  (39, '候车室', 'hòuchēshì', 'sala de espera'),
  (39, '安检', 'ānjiǎn', 'controlo de segurança'),
  (39, '检票口', 'jiǎnpiàokǒu', 'porta de embarque'),
  (39, '座位', 'zuòwèi', 'lugar sentado'),
  (39, '行李', 'xíngli', 'bagagem'),
  (40, '酒店', 'jiǔdiàn', 'hotel'),
  (40, '订', 'dìng', 'reservar'),
  (40, '房间', 'fángjiān', 'quarto'),
  (40, '住', 'zhù', 'ficar / morar'),
  (40, '入住', 'rùzhù', 'fazer o check-in'),
  (40, '房卡', 'fángkǎ', 'cartão do quarto'),
  (40, '押金', 'yājīn', 'caução'),
  (41, '毛巾', 'máojīn', 'toalha'),
  (41, '条', 'tiáo', 'classificador de coisas compridas'),
  (41, '空调', 'kōngtiáo', 'ar condicionado'),
  (41, '坏', 'huài', 'avariado / estragado'),
  (41, '热水', 'rèshuǐ', 'água quente'),
  (41, '早餐', 'zǎocān', 'pequeno-almoço (no hotel)'),
  (41, '开始', 'kāishǐ', 'começar'),
  (42, '退房', 'tuìfáng', 'fazer o check-out'),
  (42, '寄存', 'jìcún', 'deixar guardado'),
  (42, '前台', 'qiántái', 'receção'),
  (42, '发票', 'fāpiào', 'fatura'),
  (42, '出租车', 'chūzūchē', 'táxi'),
  (42, '辆', 'liàng', 'classificador de veículos'),
  (42, '机场', 'jīchǎng', 'aeroporto'),
  (43, '山', 'shān', 'montanha'),
  (43, '河', 'hé', 'rio'),
  (43, '风景', 'fēngjǐng', 'paisagem'),
  (43, '漂亮', 'piàoliang', 'bonito'),
  (43, '真', 'zhēn', 'mesmo / tão'),
  (43, '多', 'duō', 'muitos'),
  (43, '船', 'chuán', 'barco'),
  (44, '小', 'xiǎo', 'pequeno'),
  (44, '老', 'lǎo', 'velho / antigo'),
  (44, '新', 'xīn', 'novo'),
  (44, '城市', 'chéngshì', 'cidade'),
  (44, '村子', 'cūnzi', 'aldeia'),
  (44, '安静', 'ānjìng', 'sossegado'),
  (44, '热闹', 'rènao', 'animado'),
  (44, '也', 'yě', 'também'),
  (45, '拍照', 'pāizhào', 'tirar fotografias'),
  (45, '照片', 'zhàopiàn', 'fotografia'),
  (45, '禁止', 'jìnzhǐ', 'proibido'),
  (45, '游客', 'yóukè', 'turista'),
  (45, '景点', 'jǐngdiǎn', 'ponto turístico'),
  (45, '门票', 'ménpiào', 'bilhete de entrada'),
  (45, '好看', 'hǎokàn', 'bonito (de ver)'),
  (46, '疼', 'téng', 'doer'),
  (46, '头', 'tóu', 'cabeça'),
  (46, '肚子', 'dùzi', 'barriga'),
  (46, '舒服', 'shūfu', 'bem / confortável'),
  (46, '药', 'yào', 'medicamento'),
  (46, '药店', 'yàodiàn', 'farmácia'),
  (46, '医院', 'yīyuàn', 'hospital'),
  (46, '附近', 'fùjìn', 'perto (daqui)'),
  (47, '救命', 'jiùmìng', 'socorro'),
  (47, '警察', 'jǐngchá', 'polícia'),
  (47, '救护车', 'jiùhùchē', 'ambulância'),
  (47, '快', 'kuài', 'depressa'),
  (47, '危险', 'wēixiǎn', 'perigoso'),
  (47, '小心', 'xiǎoxīn', 'cuidado'),
  (47, '着火', 'zháohuǒ', 'pegar fogo'),
  (48, '丢', 'diū', 'perder'),
  (48, '钱包', 'qiánbāo', 'carteira'),
  (48, '找', 'zhǎo', 'procurar'),
  (48, '迷路', 'mílù', 'perder-se'),
  (48, '报警', 'bàojǐng', 'chamar a polícia'),
  (48, '大使馆', 'dàshǐguǎn', 'embaixada'),
  (48, '偷', 'tōu', 'roubar'),
  (49, '比', 'bǐ', 'do que (a comparar)'),
  (49, '更', 'gèng', 'ainda mais'),
  (49, '多了', 'duō le', 'muito mais'),
  (49, '湖', 'hú', 'lago'),
  (49, '西湖', 'Xīhú', 'Lago Oeste'),
  (49, '暖和', 'nuǎnhuo', 'ameno'),
  (49, '凉快', 'liángkuai', 'fresco'),
  (50, '跟', 'gēn', 'com / e'),
  (50, '一样', 'yíyàng', 'igual'),
  (50, '不一样', 'bù yíyàng', 'diferente'),
  (50, '差不多', 'chàbuduō', 'quase igual'),
  (50, '最', 'zuì', 'o mais'),
  (50, '有名', 'yǒumíng', 'famoso'),
  (50, '龙井', 'Lóngjǐng', 'chá Longjing'),
  (51, '还是', 'háishi', 'ou (em perguntas)'),
  (51, '或者', 'huòzhě', 'ou (em afirmações)'),
  (51, '红茶', 'hóngchá', 'chá preto'),
  (51, '绿茶', 'lǜchá', 'chá verde'),
  (51, '随便', 'suíbiàn', 'tanto faz'),
  (51, '选', 'xuǎn', 'escolher'),
  (51, '大号', 'dàhào', 'tamanho grande'),
  (52, '了', 'le', 'partícula de ação terminada'),
  (52, '没', 'méi', 'não (no passado)'),
  (52, '他', 'tā', 'ele'),
  (52, '她', 'tā', 'ela'),
  (52, '已经', 'yǐjīng', 'já'),
  (52, '还没', 'hái méi', 'ainda não'),
  (52, '去年', 'qùnián', 'o ano passado'),
  (53, '过', 'guo', 'partícula de experiência'),
  (53, '从来', 'cónglái', 'nunca (com 没)'),
  (53, '次', 'cì', 'vez'),
  (53, '臭豆腐', 'chòudòufu', 'tofu fermentado'),
  (53, '爬山', 'páshān', 'subir a montanha'),
  (53, '长城', 'Chángchéng', 'Grande Muralha'),
  (53, '中国', 'Zhōngguó', 'China'),
  (54, '最后', 'zuìhòu', 'por fim'),
  (54, '的时候', 'de shíhou', 'quando'),
  (54, '旅游', 'lǚyóu', 'fazer turismo'),
  (54, '开心', 'kāixīn', 'contente'),
  (54, '得', 'de', 'partícula de modo'),
  (54, '累', 'lèi', 'cansado'),
  (54, '自行车', 'zìxíngchē', 'bicicleta'),
  (54, '可是', 'kěshì', 'mas'),
  (55, '对', 'duì', 'certo'),
  (55, '同意', 'tóngyì', 'concordar'),
  (55, '不太', 'bú tài', 'não muito'),
  (55, '意见', 'yìjiàn', 'opinião'),
  (55, '可能', 'kěnéng', 'talvez'),
  (55, '没错', 'méi cuò', 'exatamente'),
  (55, '这样', 'zhèyàng', 'assim'),
  (56, '为什么', 'wèishénme', 'porquê'),
  (56, '而且', 'érqiě', 'além disso'),
  (56, '但是', 'dànshì', 'mas'),
  (56, '虽然', 'suīrán', 'embora'),
  (56, '方便', 'fāngbiàn', 'prático'),
  (56, '重要', 'zhòngyào', 'importante'),
  (56, '好用', 'hǎoyòng', 'fácil de usar'),
  (57, '应该', 'yīnggāi', 'dever'),
  (57, '最好', 'zuìhǎo', 'o melhor é'),
  (57, '不用', 'búyòng', 'não é preciso'),
  (57, '别', 'bié', 'não (numa ordem)'),
  (57, '担心', 'dānxīn', 'preocupar-se'),
  (57, '建议', 'jiànyì', 'sugestão / sugerir'),
  (57, '早点儿', 'zǎo diǎnr', 'um pouco mais cedo'),
  (58, '网上', 'wǎngshàng', 'na internet'),
  (58, '网购', 'wǎnggòu', 'comprar pela internet'),
  (58, '快递', 'kuàidì', 'encomenda / entrega'),
  (58, '什么时候', 'shénme shíhou', 'quando'),
  (58, '地址', 'dìzhǐ', 'morada'),
  (58, '衣服', 'yīfu', 'roupa'),
  (58, '件', 'jiàn', 'classificador de roupa'),
  (59, '换', 'huàn', 'trocar'),
  (59, '退货', 'tuìhuò', 'devolver'),
  (59, '退款', 'tuìkuǎn', 'reembolso'),
  (59, '合适', 'héshì', 'ficar bem / servir'),
  (59, '颜色', 'yánsè', 'cor'),
  (59, '质量', 'zhìliàng', 'qualidade'),
  (59, '别的', 'bié de', 'outro'),
  (60, '预约', 'yùyuē', 'marcar (uma hora)'),
  (60, '取消', 'qǔxiāo', 'cancelar'),
  (60, '理发', 'lǐfà', 'cortar o cabelo'),
  (60, '位子', 'wèizi', 'lugar (à mesa)'),
  (60, '外卖', 'wàimài', 'comida para entregar'),
  (60, '服务', 'fúwù', 'serviço'),
  (60, '满意', 'mǎnyì', 'satisfeito'),
  (61, '租', 'zū', 'arrendar'),
  (61, '房子', 'fángzi', 'casa'),
  (61, '房东', 'fángdōng', 'senhorio'),
  (61, '房租', 'fángzū', 'renda'),
  (61, '合租', 'hézū', 'partilhar casa'),
  (61, '卧室', 'wòshì', 'quarto de dormir'),
  (61, '厨房', 'chúfáng', 'cozinha'),
  (61, '和', 'hé', 'e'),
  (62, '修', 'xiū', 'arranjar'),
  (62, '洗衣机', 'xǐyījī', 'máquina de lavar'),
  (62, '灯', 'dēng', 'luz / candeeiro'),
  (62, '漏水', 'lòushuǐ', 'ter uma fuga de água'),
  (62, '一下', 'yíxià', 'um pouco (suaviza o pedido)'),
  (62, '师傅', 'shīfu', 'técnico / mestre'),
  (62, '来', 'lái', 'vir'),
  (63, '小区', 'xiǎoqū', 'condomínio'),
  (63, '邻居', 'línjū', 'vizinho'),
  (63, '超市', 'chāoshì', 'supermercado'),
  (63, '保安', 'bǎo''ān', 'segurança (pessoa)'),
  (63, '楼', 'lóu', 'prédio / andar'),
  (63, '电梯', 'diàntī', 'elevador'),
  (63, '楼梯', 'lóutī', 'escadas'),
  (64, '办公室', 'bàngōngshì', 'escritório'),
  (64, '同事', 'tóngshì', 'colega'),
  (64, '经理', 'jīnglǐ', 'diretor'),
  (64, '开会', 'kāihuì', 'ter uma reunião'),
  (64, '电脑', 'diànnǎo', 'computador'),
  (64, '打印', 'dǎyìn', 'imprimir'),
  (64, '文件', 'wénjiàn', 'documento'),
  (65, '邮件', 'yóujiàn', 'e-mail'),
  (65, '以前', 'yǐqián', 'antes de'),
  (65, '以后', 'yǐhòu', 'depois de'),
  (65, '得', 'děi', 'ter de'),
  (65, '加班', 'jiābān', 'fazer horas extra'),
  (65, '完成', 'wánchéng', 'terminar'),
  (65, '任务', 'rènwu', 'tarefa'),
  (66, '喂', 'wéi', 'está? (ao telefone)'),
  (66, '回电话', 'huí diànhuà', 'ligar de volta'),
  (66, '号码', 'hàomǎ', 'número'),
  (66, '稍等', 'shāo děng', 'um momento'),
  (66, '让', 'ràng', 'pedir a alguém / deixar'),
  (66, '留言', 'liúyán', 'deixar recado'),
  (66, '打错了', 'dǎ cuò le', 'enganou-se no número'),
  (67, '面试', 'miànshì', 'entrevista'),
  (67, '介绍', 'jièshào', 'apresentar'),
  (67, '自己', 'zìjǐ', 'a mim mesmo / a si mesmo'),
  (67, '大学', 'dàxué', 'universidade'),
  (67, '毕业', 'bìyè', 'acabar o curso'),
  (67, '专业', 'zhuānyè', 'área de estudo'),
  (67, '计算机', 'jìsuànjī', 'informática'),
  (68, '经验', 'jīngyàn', 'experiência'),
  (68, '家', 'jiā', 'classificador de empresas e lojas'),
  (68, '葡萄牙语', 'Pútáoyáyǔ', 'português (língua)'),
  (68, '英语', 'Yīngyǔ', 'inglês'),
  (68, '编程', 'biānchéng', 'programar'),
  (68, '团队', 'tuánduì', 'equipa'),
  (68, '能力', 'nénglì', 'capacidade'),
  (69, '工资', 'gōngzī', 'salário'),
  (69, '合同', 'hétong', 'contrato'),
  (69, '休假', 'xiūjià', 'férias'),
  (69, '天', 'tiān', 'dia'),
  (69, '机会', 'jīhuì', 'oportunidade'),
  (69, '希望', 'xīwàng', 'esperar / desejar'),
  (69, '问题', 'wèntí', 'pergunta / problema'),
  (70, '东', 'dōng', 'este'),
  (70, '南', 'nán', 'sul'),
  (70, '西', 'xī', 'oeste'),
  (70, '北', 'běi', 'norte'),
  (70, '路', 'lù', 'rua / estrada'),
  (70, '街', 'jiē', 'rua'),
  (70, '路口', 'lùkǒu', 'cruzamento'),
  (71, '请勿', 'qǐngwù', 'por favor, não'),
  (71, '吸烟', 'xīyān', 'fumar'),
  (71, '注意', 'zhùyì', 'atenção'),
  (71, '滑', 'huá', 'escorregadio'),
  (71, '入口', 'rùkǒu', 'entrada'),
  (71, '推', 'tuī', 'empurrar'),
  (71, '拉', 'lā', 'puxar'),
  (72, '号线', 'hàoxiàn', 'linha (de metro)'),
  (72, '换乘', 'huànchéng', 'mudar de linha'),
  (72, '下一站', 'xià yí zhàn', 'próxima estação'),
  (72, '营业时间', 'yíngyè shíjiān', 'horário de funcionamento'),
  (72, '打折', 'dǎzhé', 'fazer desconto'),
  (72, '开门', 'kāimén', 'abrir'),
  (72, '关门', 'guānmén', 'fechar');

-- Frases de exemplo de cada lição
INSERT INTO frases (licao_id, hanzi, pinyin, traducao) VALUES
  (1, '妈妈骂马吗？', 'Māma mà mǎ ma?', 'A mãe ralha com o cavalo?'),
  (2, '我吃鸡。', 'Wǒ chī jī.', 'Eu como galinha.'),
  (2, '中国人很高。', 'Zhōngguó rén hěn gāo.', 'Os chineses são altos.'),
  (3, '我爱我的狗。', 'Wǒ ài wǒ de gǒu.', 'Adoro o meu cão.'),
  (3, '我吃鱼和饭。', 'Wǒ chī yú hé fàn.', 'Eu como peixe e arroz.'),
  (4, '你好！', 'Nǐ hǎo!', 'Olá!'),
  (4, '您好，老师！', 'Nín hǎo, lǎoshī!', 'Olá, professor!'),
  (4, '谢谢！不客气。', 'Xièxie! Bú kèqi.', 'Obrigado! De nada.'),
  (4, '对不起！', 'Duìbuqǐ!', 'Desculpa!'),
  (4, '再见！', 'Zàijiàn!', 'Adeus!'),
  (5, '你叫什么名字？', 'Nǐ jiào shénme míngzi?', 'Como te chamas?'),
  (5, '我叫玛丽亚。', 'Wǒ jiào Mǎlìyà.', 'Chamo-me Maria.'),
  (5, '您叫什么名字？', 'Nín jiào shénme míngzi?', 'Como se chama? (formal)'),
  (6, '你是哪国人？', 'Nǐ shì nǎ guó rén?', 'De que país és?'),
  (6, '我是葡萄牙人。', 'Wǒ shì Pútáoyá rén.', 'Sou português.'),
  (6, '你是巴西人吗？', 'Nǐ shì Bāxī rén ma?', 'És brasileiro?'),
  (6, '不是，我是葡萄牙人。你呢？', 'Bú shì, wǒ shì Pútáoyá rén. Nǐ ne?', 'Não, sou português. E tu?'),
  (6, '我是中国人。', 'Wǒ shì Zhōngguó rén.', 'Sou chinês.'),
  (7, '一二三四五', 'yī èr sān sì wǔ', 'um, dois, três, quatro, cinco'),
  (7, '六七八九十', 'liù qī bā jiǔ shí', 'seis, sete, oito, nove, dez'),
  (8, '你几岁？', 'Nǐ jǐ suì?', 'Quantos anos tens? (a uma criança)'),
  (8, '你多大？', 'Nǐ duō dà?', 'Que idade tens?'),
  (8, '我二十五岁。', 'Wǒ èrshíwǔ suì.', 'Tenho vinte e cinco anos.'),
  (9, '我家有四个人。', 'Wǒ jiā yǒu sì ge rén.', 'Na minha família somos quatro.'),
  (9, '我有一个哥哥。', 'Wǒ yǒu yí ge gēge.', 'Tenho um irmão mais velho.'),
  (9, '我没有妹妹。', 'Wǒ méiyǒu mèimei.', 'Não tenho irmãs mais novas.'),
  (9, '这是我的妈妈。', 'Zhè shì wǒ de māma.', 'Esta é a minha mãe.'),
  (10, '今天星期几？', 'Jīntiān xīngqī jǐ?', 'Que dia da semana é hoje?'),
  (10, '今天星期三。', 'Jīntiān xīngqīsān.', 'Hoje é quarta-feira.'),
  (10, '明天星期四。', 'Míngtiān xīngqīsì.', 'Amanhã é quinta-feira.'),
  (11, '今天几月几号？', 'Jīntiān jǐ yuè jǐ hào?', 'Que dia é hoje?'),
  (11, '今天九月二十八号。', 'Jīntiān jiǔ yuè èrshíbā hào.', 'Hoje é dia 28 de setembro.'),
  (11, '我的生日是五月三号。', 'Wǒ de shēngrì shì wǔ yuè sān hào.', 'O meu aniversário é a 3 de maio.'),
  (12, '现在几点？', 'Xiànzài jǐ diǎn?', 'Que horas são?'),
  (12, '现在三点半。', 'Xiànzài sān diǎn bàn.', 'São três e meia.'),
  (12, '我下午两点上课。', 'Wǒ xiàwǔ liǎng diǎn shàngkè.', 'Tenho aula às duas da tarde.'),
  (13, '老板，我要一个肉夹馍。', 'Lǎobǎn, wǒ yào yí ge ròujiāmó.', 'Queria um pão com carne, se faz favor.'),
  (13, '请给我这个。', 'Qǐng gěi wǒ zhège.', 'Dá-me este, por favor.'),
  (13, '你要什么？', 'Nǐ yào shénme?', 'O que queres?'),
  (14, '我想喝茶。', 'Wǒ xiǎng hē chá.', 'Apetece-me beber chá.'),
  (14, '你想吃什么？', 'Nǐ xiǎng chī shénme?', 'O que te apetece comer?'),
  (14, '我想吃饺子。', 'Wǒ xiǎng chī jiǎozi.', 'Apetece-me comer jiaozi.'),
  (15, '这个很好吃！', 'Zhège hěn hǎochī!', 'Isto é muito bom!'),
  (15, '太辣了！', 'Tài là le!', 'É demasiado picante!'),
  (15, '不要辣，谢谢。', 'Bú yào là, xièxie.', 'Sem picante, obrigado.'),
  (16, '这个多少钱？', 'Zhège duōshao qián?', 'Quanto custa isto?'),
  (16, '十五块。', 'Shíwǔ kuài.', 'Quinze yuan.'),
  (16, '一共多少钱？', 'Yígòng duōshao qián?', 'Quanto é no total?'),
  (17, '我要两碗面。', 'Wǒ yào liǎng wǎn miàn.', 'Quero duas tigelas de massa.'),
  (17, '一瓶水多少钱？', 'Yì píng shuǐ duōshao qián?', 'Quanto custa uma garrafa de água?'),
  (17, '苹果一斤五块。', 'Píngguǒ yì jīn wǔ kuài.', 'As maçãs custam cinco yuan o meio quilo.'),
  (18, '太贵了！', 'Tài guì le!', 'É demasiado caro!'),
  (18, '便宜一点儿吧。', 'Piányi yìdiǎnr ba.', 'Faz um pouco mais barato.'),
  (18, '二十块，可以吗？', 'Èrshí kuài, kěyǐ ma?', 'Vinte yuan, pode ser?'),
  (19, '请问，厕所在哪儿？', 'Qǐngwèn, cèsuǒ zài nǎr?', 'Desculpe, onde fica a casa de banho?'),
  (19, '地铁站在那儿。', 'Dìtiězhàn zài nàr.', 'A estação de metro é ali.'),
  (19, '银行在哪儿？', 'Yínháng zài nǎr?', 'Onde fica o banco?'),
  (20, '往左拐。', 'Wǎng zuǒ guǎi.', 'Vira à esquerda.'),
  (20, '一直往前走。', 'Yìzhí wǎng qián zǒu.', 'Segue sempre em frente.'),
  (20, '银行在地铁站旁边。', 'Yínháng zài dìtiězhàn pángbiān.', 'O banco fica ao lado da estação de metro.'),
  (21, '城墙离这儿远吗？', 'Chéngqiáng lí zhèr yuǎn ma?', 'A muralha fica longe daqui?'),
  (21, '不远，走路十分钟。', 'Bù yuǎn, zǒulù shí fēnzhōng.', 'Não, são dez minutos a pé.'),
  (21, '去地铁站怎么走？', 'Qù dìtiězhàn zěnme zǒu?', 'Como se vai para a estação de metro?'),
  (22, '可以用支付宝吗？', 'Kěyǐ yòng Zhīfùbǎo ma?', 'Posso pagar com Alipay?'),
  (22, '请扫这个码。', 'Qǐng sǎo zhège mǎ.', 'Lê este código, por favor.'),
  (22, '我没有现金。', 'Wǒ méiyǒu xiànjīn.', 'Não tenho notas nem moedas.'),
  (23, '明天上午我想去看兵马俑。', 'Míngtiān shàngwǔ wǒ xiǎng qù kàn Bīngmǎyǒng.', 'Amanhã de manhã quero ir ver os Guerreiros de Terracota.'),
  (23, '我们先吃饭，然后去城墙。', 'Wǒmen xiān chīfàn, ránhòu qù chéngqiáng.', 'Primeiro comemos e depois vamos à muralha.'),
  (23, '晚上一起去吃饺子吧！', 'Wǎnshang yìqǐ qù chī jiǎozi ba!', 'À noite vamos juntos comer jiaozi!'),
  (24, '我听不懂。', 'Wǒ tīng bu dǒng.', 'Não percebo.'),
  (24, '请说慢一点儿。', 'Qǐng shuō màn yìdiǎnr.', 'Fala mais devagar, por favor.'),
  (24, '请再说一遍。', 'Qǐng zài shuō yí biàn.', 'Repete, por favor.'),
  (24, '可以帮我吗？', 'Kěyǐ bāng wǒ ma?', 'Podes ajudar-me?'),
  (25, '我每天早上七点起床。', 'Wǒ měitiān zǎoshang qī diǎn qǐchuáng.', 'Todos os dias levanto-me às sete da manhã.'),
  (25, '你几点睡觉？', 'Nǐ jǐ diǎn shuìjiào?', 'A que horas te deitas?'),
  (25, '我每天都吃早饭。', 'Wǒ měitiān dōu chī zǎofàn.', 'Tomo sempre o pequeno-almoço.'),
  (26, '我坐地铁去公司。', 'Wǒ zuò dìtiě qù gōngsī.', 'Vou de metro para a empresa.'),
  (26, '你几点下班？', 'Nǐ jǐ diǎn xiàbān?', 'A que horas sais do trabalho?'),
  (26, '我在学校学习中文。', 'Wǒ zài xuéxiào xuéxí Zhōngwén.', 'Estudo chinês na escola.'),
  (27, '周末我常常在家休息。', 'Zhōumò wǒ chángcháng zài jiā xiūxi.', 'Ao fim de semana descanso muitas vezes em casa.'),
  (27, '我有时候做饭。', 'Wǒ yǒu shíhou zuòfàn.', 'Às vezes cozinho.'),
  (27, '星期六我去见朋友。', 'Xīngqīliù wǒ qù jiàn péngyou.', 'No sábado vou ter com amigos.'),
  (28, '你喜欢什么？', 'Nǐ xǐhuan shénme?', 'De que gostas?'),
  (28, '我很喜欢看电影。', 'Wǒ hěn xǐhuan kàn diànyǐng.', 'Gosto muito de ver filmes.'),
  (28, '你喜欢不喜欢唱歌？', 'Nǐ xǐhuan bu xǐhuan chànggē?', 'Gostas de cantar?'),
  (29, '你会打麻将吗？', 'Nǐ huì dǎ májiàng ma?', 'Sabes jogar mahjong?'),
  (29, '我不会，你教我吧！', 'Wǒ bú huì, nǐ jiāo wǒ ba!', 'Não sei, ensina-me!'),
  (29, '我们去茶馆喝茶吧。', 'Wǒmen qù cháguǎn hē chá ba.', 'Vamos beber chá à casa de chá.'),
  (30, '这个电影怎么样？', 'Zhège diànyǐng zěnmeyàng?', 'Que tal este filme?'),
  (30, '我觉得非常有意思。', 'Wǒ juéde fēicháng yǒu yìsi.', 'Acho que é muito interessante.'),
  (30, '成都很好玩！', 'Chéngdū hěn hǎowán!', 'Chengdu é muito divertida!'),
  (30, '这个有点儿辣。', 'Zhège yǒudiǎnr là.', 'Isto é um bocado picante.'),
  (31, '你今天晚上有空吗？', 'Nǐ jīntiān wǎnshang yǒu kòng ma?', 'Estás livre hoje à noite?'),
  (31, '我们一起吃火锅吧！', 'Wǒmen yìqǐ chī huǒguō ba!', 'Vamos comer hotpot juntos!'),
  (31, '行！今天我请客。', 'Xíng! Jīntiān wǒ qǐngkè.', 'Combinado! Hoje pago eu.'),
  (31, '对不起，我今天很忙。', 'Duìbuqǐ, wǒ jīntiān hěn máng.', 'Desculpa, hoje estou muito ocupado.'),
  (32, '我们几点见面？', 'Wǒmen jǐ diǎn jiànmiàn?', 'A que horas nos encontramos?'),
  (32, '七点在饭馆门口见。', 'Qī diǎn zài fànguǎn ménkǒu jiàn.', 'Às sete à porta do restaurante.'),
  (32, '我到了，在门口等你。', 'Wǒ dào le, zài ménkǒu děng nǐ.', 'Já cheguei, estou à tua espera à porta.'),
  (32, '不见不散！', 'Bú jiàn bú sàn!', 'Lá estarei sem falta!'),
  (33, '服务员，请给我菜单。', 'Fúwùyuán, qǐng gěi wǒ càidān.', 'Se faz favor, a ementa.'),
  (33, '我们要一个鸳鸯锅，微辣。', 'Wǒmen yào yí ge yuānyang guō, wēilà.', 'Queremos uma panela de duas metades, pouco picante.'),
  (33, '服务员，买单！', 'Fúwùyuán, mǎidān!', 'A conta, se faz favor!'),
  (34, '今天天气怎么样？', 'Jīntiān tiānqì zěnmeyàng?', 'Como está o tempo hoje?'),
  (34, '下雨了！', 'Xià yǔ le!', 'Começou a chover!'),
  (34, '明天下雨，带伞吧。', 'Míngtiān xià yǔ, dài sǎn ba.', 'Amanhã chove, leva o guarda-chuva.'),
  (34, '成都的夏天很热。', 'Chéngdū de xiàtiān hěn rè.', 'O verão em Chengdu é muito quente.'),
  (35, '我加你微信吧。', 'Wǒ jiā nǐ Wēixìn ba.', 'Deixa-me adicionar-te no WeChat.'),
  (35, '到了给我发消息。', 'Dào le gěi wǒ fā xiāoxi.', 'Quando chegares, manda-me uma mensagem.'),
  (35, '我给你打电话。', 'Wǒ gěi nǐ dǎ diànhuà.', 'Eu telefono-te.'),
  (36, '不好意思，我今天不能去。', 'Bù hǎoyìsi, wǒ jīntiān bù néng qù.', 'Desculpa, hoje não posso ir.'),
  (36, '因为下雨，所以我迟到了。', 'Yīnwèi xià yǔ, suǒyǐ wǒ chídào le.', 'Como choveu, cheguei atrasado.'),
  (36, '没关系，我们改天吧！', 'Méi guānxi, wǒmen gǎitiān ba!', 'Não faz mal, fica para outro dia!'),
  (37, '我要买一张去桂林的票。', 'Wǒ yào mǎi yì zhāng qù Guìlín de piào.', 'Quero comprar um bilhete para Guilin.'),
  (37, '请给我看一下您的护照。', 'Qǐng gěi wǒ kàn yíxià nín de hùzhào.', 'Mostre-me o seu passaporte, por favor.'),
  (37, '单程还是往返？', 'Dānchéng háishi wǎngfǎn?', 'Só ida ou ida e volta?'),
  (38, '火车几点开？', 'Huǒchē jǐ diǎn kāi?', 'A que horas parte o comboio?'),
  (38, '从成都到桂林要多长时间？', 'Cóng Chéngdū dào Guìlín yào duō cháng shíjiān?', 'Quanto tempo demora de Chengdu a Guilin?'),
  (38, '大概五个小时。', 'Dàgài wǔ ge xiǎoshí.', 'Mais ou menos cinco horas.'),
  (39, '请问，候车室在哪儿？', 'Qǐngwèn, hòuchēshì zài nǎr?', 'Desculpe, onde é a sala de espera?'),
  (39, '这是我的座位。', 'Zhè shì wǒ de zuòwèi.', 'Este é o meu lugar.'),
  (39, '行李要安检。', 'Xíngli yào ānjiǎn.', 'A bagagem tem de passar no controlo.'),
  (40, '我订了一个房间。', 'Wǒ dìngle yí ge fángjiān.', 'Reservei um quarto.'),
  (40, '我住三个晚上。', 'Wǒ zhù sān ge wǎnshang.', 'Fico três noites.'),
  (40, '这是您的房卡。', 'Zhè shì nín de fángkǎ.', 'Aqui tem o cartão do quarto.'),
  (41, '能不能给我一条毛巾？', 'Néng bu néng gěi wǒ yì tiáo máojīn?', 'Pode dar-me uma toalha?'),
  (41, '房间的空调坏了。', 'Fángjiān de kōngtiáo huài le.', 'O ar condicionado do quarto está avariado.'),
  (41, '早餐几点开始？', 'Zǎocān jǐ diǎn kāishǐ?', 'A que horas começa o pequeno-almoço?'),
  (42, '我要退房。', 'Wǒ yào tuìfáng.', 'Queria fazer o check-out.'),
  (42, '可以寄存行李吗？', 'Kěyǐ jìcún xíngli ma?', 'Posso deixar cá a bagagem?'),
  (42, '请帮我叫一辆出租车。', 'Qǐng bāng wǒ jiào yí liàng chūzūchē.', 'Chame-me um táxi, por favor.'),
  (43, '这儿的风景真漂亮！', 'Zhèr de fēngjǐng zhēn piàoliang!', 'A paisagem daqui é mesmo bonita!'),
  (43, '桂林有很多山。', 'Guìlín yǒu hěn duō shān.', 'Guilin tem muitas montanhas.'),
  (43, '我们坐船去吧。', 'Wǒmen zuò chuán qù ba.', 'Vamos de barco.'),
  (44, '桂林是一个很漂亮的城市。', 'Guìlín shì yí ge hěn piàoliang de chéngshì.', 'Guilin é uma cidade muito bonita.'),
  (44, '这个村子很老，也很安静。', 'Zhège cūnzi hěn lǎo, yě hěn ānjìng.', 'Esta aldeia é muito antiga e também muito sossegada.'),
  (44, '晚上街上很热闹。', 'Wǎnshang jiē shang hěn rènao.', 'À noite as ruas estão muito animadas.'),
  (45, '可以帮我拍一张照吗？', 'Kěyǐ bāng wǒ pāi yì zhāng zhào ma?', 'Podes tirar-me uma fotografia?'),
  (45, '这里可以拍照吗？', 'Zhèlǐ kěyǐ pāizhào ma?', 'Pode-se fotografar aqui?'),
  (45, '这张照片很好看！', 'Zhè zhāng zhàopiàn hěn hǎokàn!', 'Esta fotografia ficou muito bonita!'),
  (46, '我不舒服。', 'Wǒ bù shūfu.', 'Não me sinto bem.'),
  (46, '我头疼。', 'Wǒ tóu téng.', 'Dói-me a cabeça.'),
  (46, '附近有药店吗？', 'Fùjìn yǒu yàodiàn ma?', 'Há alguma farmácia aqui perto?'),
  (47, '救命！', 'Jiùmìng!', 'Socorro!'),
  (47, '快叫救护车！', 'Kuài jiào jiùhùchē!', 'Chamem uma ambulância, depressa!'),
  (47, '小心，危险！', 'Xiǎoxīn, wēixiǎn!', 'Cuidado, é perigoso!'),
  (48, '我的钱包丢了。', 'Wǒ de qiánbāo diū le.', 'Perdi a carteira.'),
  (48, '我迷路了，你能帮我吗？', 'Wǒ mílù le, nǐ néng bāng wǒ ma?', 'Perdi-me, podes ajudar-me?'),
  (48, '葡萄牙大使馆在哪儿？', 'Pútáoyá dàshǐguǎn zài nǎr?', 'Onde fica a Embaixada de Portugal?'),
  (49, '杭州比上海小。', 'Hángzhōu bǐ Shànghǎi xiǎo.', 'Hangzhou é mais pequena do que Xangai.'),
  (49, '西湖比我想的更漂亮。', 'Xīhú bǐ wǒ xiǎng de gèng piàoliang.', 'O Lago Oeste é ainda mais bonito do que eu pensava.'),
  (49, '今天比昨天凉快多了。', 'Jīntiān bǐ zuótiān liángkuai duō le.', 'Hoje está muito mais fresco do que ontem.'),
  (50, '我跟你一样高。', 'Wǒ gēn nǐ yíyàng gāo.', 'Sou tão alto como tu.'),
  (50, '杭州没有上海大。', 'Hángzhōu méiyǒu Shànghǎi dà.', 'Hangzhou não é tão grande como Xangai.'),
  (50, '龙井是杭州最有名的茶。', 'Lóngjǐng shì Hángzhōu zuì yǒumíng de chá.', 'O Longjing é o chá mais famoso de Hangzhou.'),
  (51, '你喝红茶还是绿茶？', 'Nǐ hē hóngchá háishi lǜchá?', 'Bebes chá preto ou chá verde?'),
  (51, '都可以，随便。', 'Dōu kěyǐ, suíbiàn.', 'Qualquer um serve, tanto faz.'),
  (51, '我们星期六或者星期天去。', 'Wǒmen xīngqīliù huòzhě xīngqītiān qù.', 'Vamos no sábado ou no domingo.'),
  (52, '我昨天去了西湖。', 'Wǒ zuótiān qùle Xīhú.', 'Ontem fui ao Lago Oeste.'),
  (52, '你吃饭了没有？', 'Nǐ chīfàn le méiyǒu?', 'Já comeste?'),
  (52, '我还没吃。', 'Wǒ hái méi chī.', 'Ainda não comi.'),
  (52, '她已经走了。', 'Tā yǐjīng zǒu le.', 'Ela já se foi embora.'),
  (53, '你去过长城吗？', 'Nǐ qùguo Chángchéng ma?', 'Já foste à Grande Muralha?'),
  (53, '我去过两次。', 'Wǒ qùguo liǎng cì.', 'Já fui duas vezes.'),
  (53, '我从来没吃过臭豆腐。', 'Wǒ cónglái méi chīguo chòudòufu.', 'Nunca comi tofu fermentado.'),
  (54, '在杭州的时候，我们骑自行车去了西湖。', 'Zài Hángzhōu de shíhou, wǒmen qí zìxíngchē qùle Xīhú.', 'Quando estivemos em Hangzhou, fomos de bicicleta ao Lago Oeste.'),
  (54, '我们玩得很开心。', 'Wǒmen wán de hěn kāixīn.', 'Divertimo-nos muito.'),
  (54, '最后我们很累，可是很开心。', 'Zuìhòu wǒmen hěn lèi, kěshì hěn kāixīn.', 'No fim estávamos cansados, mas muito contentes.'),
  (55, '对，我同意。', 'Duì, wǒ tóngyì.', 'Sim, concordo.'),
  (55, '我不太同意你的意见。', 'Wǒ bú tài tóngyì nǐ de yìjiàn.', 'Não concordo muito com a tua opinião.'),
  (55, '可能你说得对。', 'Kěnéng nǐ shuō de duì.', 'Talvez tenhas razão.'),
  (56, '你为什么喜欢杭州？', 'Nǐ wèishénme xǐhuan Hángzhōu?', 'Porque gostas de Hangzhou?'),
  (56, '因为杭州很漂亮，而且很安静。', 'Yīnwèi Hángzhōu hěn piàoliang, érqiě hěn ānjìng.', 'Porque Hangzhou é muito bonita e, além disso, muito sossegada.'),
  (56, '虽然很贵，但是很方便。', 'Suīrán hěn guì, dànshì hěn fāngbiàn.', 'Embora seja caro, é muito prático.'),
  (57, '你应该多休息。', 'Nǐ yīnggāi duō xiūxi.', 'Deves descansar mais.'),
  (57, '最好早点儿去。', 'Zuìhǎo zǎo diǎnr qù.', 'O melhor é ir um pouco mais cedo.'),
  (57, '别担心！', 'Bié dānxīn!', 'Não te preocupes!'),
  (58, '我在网上买了一件衣服。', 'Wǒ zài wǎngshàng mǎile yí jiàn yīfu.', 'Comprei uma peça de roupa pela internet.'),
  (58, '快递什么时候到？', 'Kuàidì shénme shíhou dào?', 'Quando chega a encomenda?'),
  (58, '请写一下你的地址。', 'Qǐng xiě yíxià nǐ de dìzhǐ.', 'Escreve a tua morada, por favor.'),
  (59, '这件衣服太小了，可以换吗？', 'Zhè jiàn yīfu tài xiǎo le, kěyǐ huàn ma?', 'Esta roupa é demasiado pequena, posso trocá-la?'),
  (59, '我想退货。', 'Wǒ xiǎng tuìhuò.', 'Quero devolver isto.'),
  (59, '有没有别的颜色？', 'Yǒu méiyǒu bié de yánsè?', 'Tem outras cores?'),
  (60, '我想预约明天下午三点。', 'Wǒ xiǎng yùyuē míngtiān xiàwǔ sān diǎn.', 'Queria marcar para amanhã às três da tarde.'),
  (60, '我要取消预约。', 'Wǒ yào qǔxiāo yùyuē.', 'Quero cancelar a marcação.'),
  (60, '我们叫外卖吧！', 'Wǒmen jiào wàimài ba!', 'Vamos pedir comida para casa!'),
  (61, '我想租一个房子。', 'Wǒ xiǎng zū yí ge fángzi.', 'Quero arrendar uma casa.'),
  (61, '房租一个月多少钱？', 'Fángzū yí ge yuè duōshao qián?', 'Quanto é a renda por mês?'),
  (61, '有两个卧室和一个厨房。', 'Yǒu liǎng ge wòshì hé yí ge chúfáng.', 'Tem dois quartos e uma cozinha.'),
  (62, '洗衣机坏了。', 'Xǐyījī huài le.', 'A máquina de lavar avariou.'),
  (62, '师傅，你能来修一下吗？', 'Shīfu, nǐ néng lái xiū yíxià ma?', 'Pode vir arranjá-la?'),
  (62, '厨房漏水了。', 'Chúfáng lòushuǐ le.', 'Há uma fuga de água na cozinha.'),
  (63, '我家附近有一个超市。', 'Wǒ jiā fùjìn yǒu yí ge chāoshì.', 'Perto da minha casa há um supermercado.'),
  (63, '我住在一楼。', 'Wǒ zhù zài yī lóu.', 'Moro no rés-do-chão.'),
  (63, '电梯坏了，我们走楼梯吧。', 'Diàntī huài le, wǒmen zǒu lóutī ba.', 'O elevador avariou, vamos pelas escadas.'),
  (64, '经理在开会。', 'Jīnglǐ zài kāihuì.', 'O diretor está em reunião.'),
  (64, '这是我的同事。', 'Zhè shì wǒ de tóngshì.', 'Este é o meu colega.'),
  (64, '请帮我打印这个文件。', 'Qǐng bāng wǒ dǎyìn zhège wénjiàn.', 'Imprime-me este documento, por favor.'),
  (65, '请星期五以前给我发邮件。', 'Qǐng xīngqīwǔ yǐqián gěi wǒ fā yóujiàn.', 'Manda-me o e-mail antes de sexta-feira, por favor.'),
  (65, '今天我得加班。', 'Jīntiān wǒ děi jiābān.', 'Hoje tenho de fazer horas extra.'),
  (65, '这个任务完成了吗？', 'Zhège rènwu wánchéng le ma?', 'Esta tarefa já está terminada?'),
  (66, '喂，请问王经理在吗？', 'Wéi, qǐngwèn Wáng jīnglǐ zài ma?', 'Está? O diretor Wang está?'),
  (66, '请稍等。', 'Qǐng shāo děng.', 'Um momento, por favor.'),
  (66, '他不在，我让他给你回电话。', 'Tā bú zài, wǒ ràng tā gěi nǐ huí diànhuà.', 'Ele não está, vou pedir-lhe que te ligue de volta.'),
  (67, '我先介绍一下自己。', 'Wǒ xiān jièshào yíxià zìjǐ.', 'Primeiro, vou apresentar-me.'),
  (67, '我学的是计算机。', 'Wǒ xué de shì jìsuànjī.', 'Estudei informática.'),
  (67, '我去年大学毕业。', 'Wǒ qùnián dàxué bìyè.', 'Acabei a universidade no ano passado.'),
  (68, '我在一家公司工作过两年。', 'Wǒ zài yì jiā gōngsī gōngzuòguo liǎng nián.', 'Trabalhei dois anos numa empresa.'),
  (68, '我会说葡萄牙语、英语和一点儿中文。', 'Wǒ huì shuō Pútáoyáyǔ, Yīngyǔ hé yìdiǎnr Zhōngwén.', 'Falo português, inglês e um pouco de chinês.'),
  (68, '我会编程，也喜欢在团队里工作。', 'Wǒ huì biānchéng, yě xǐhuan zài tuánduì lǐ gōngzuò.', 'Sei programar e também gosto de trabalhar em equipa.'),
  (69, '每天工作几个小时？', 'Měitiān gōngzuò jǐ ge xiǎoshí?', 'Quantas horas se trabalha por dia?'),
  (69, '一年有几天休假？', 'Yì nián yǒu jǐ tiān xiūjià?', 'Quantos dias de férias há por ano?'),
  (69, '谢谢您给我这个机会。', 'Xièxie nín gěi wǒ zhège jīhuì.', 'Obrigado por me dar esta oportunidade.'),
  (70, '南京东路在哪儿？', 'Nánjīng Dōng Lù zài nǎr?', 'Onde fica a Rua de Nanquim Este?'),
  (70, '往北走五分钟。', 'Wǎng běi zǒu wǔ fēnzhōng.', 'Anda cinco minutos para norte.'),
  (70, '地铁站在路口。', 'Dìtiězhàn zài lùkǒu.', 'A estação de metro fica no cruzamento.'),
  (71, '禁止吸烟。', 'Jìnzhǐ xīyān.', 'Proibido fumar.'),
  (71, '小心地滑！', 'Xiǎoxīn dì huá!', 'Cuidado, piso escorregadio!'),
  (71, '请勿触摸。', 'Qǐngwù chùmō.', 'Não tocar, por favor.'),
  (72, '去外滩在哪儿换乘？', 'Qù Wàitān zài nǎr huànchéng?', 'Onde mudo de linha para ir ao Bund?'),
  (72, '下一站，人民广场。', 'Xià yí zhàn, Rénmín Guǎngchǎng.', 'Próxima estação: Praça do Povo.'),
  (72, '今天全场打八折！', 'Jīntiān quánchǎng dǎ bā zhé!', 'Hoje tudo com 20% de desconto!');
